spring.sendgrid.api-key: "api_sendgrid_here"
spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
